[build]
  publish = "."
  functions = "register/netlify/functions"

[dev]
  framework = "#static"
  publish = "."

[[redirects]]
  from = "/register/*"
  to = "/register/:splat"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register/index.html"
  status = 200
